In [74]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [75]:
df=pd.read_csv("student_habits_performance.csv")

In [76]:
df.head()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4

In [77]:
df.tail()

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [78]:
df.shape

(1000, 16)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     1000 non-null   object
 1   age                            1000 non-null   int64
 2   gender                         1000 non-null   object
 3   study_hours_per_day            1000 non-null   float64
 4   social_media_hours             1000 non-null   float64
 5   netflix_hours                  1000 non-null   float64
 6   part_time_job                  1000 non-null   object
 7   attendance_percentage          1000 non-null   float64
 8   sleep_hours                    1000 non-null   float64
 9   diet_quality                   1000 non-null   object
 10  exercise_frequency             1000 non-null   int64
 11  parental_education_level       909 non-null    object
 12  internet_quality               1000 non-null   object
 13  mental_health_rating           1000 non-null   int64
 14  extracurricular_participation  1000 non-null   object
 15  exam_score                     1000 non-null   float64
dtypes: float64(6), int64(3), object(7)
memory usage: 125.1+ KB

In [80]:
df.isna().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [81]:
df.describe()

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score
count,1000.0000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.4980,3.55010,2.505500,1.819700,84.131700,6.470100,3.042000,5.438000,69.601500
std,2.3081,1.46889,1.172422,1.075118,9.399246,1.226377,2.025423,2.847501,16.888564
min,17.0000,0.00000,0.000000,0.000000,56.000000,3.200000,0.000000,1.000000,18.400000
25%,18.7500,2.60000,1.700000,1.000000,78.000000,5.600000,1.000000,3.000000,58.475000
50%,20.0000,3.50000,2.500000,1.800000,84.400000,6.500000,3.000000,5.000000,70.500000
75%,23.0000,4.50000,3.300000,2.525000,91.025000,7.300000,5.000000,8.000000,81.325000
max,24.0000,8.30000,7.200000,5.400000,100.000000,10.000000,6.000000,10.000000,100.000000

In [82]:
# df.dtypes

In [83]:
# df.index
# df.columns

In [84]:
df.drop('parental_education_level',axis=1)#  drop  [ parental_education_level ]

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Average,8,No,74.9

In [85]:
df.dropna(inplace=True)

In [86]:
df.duplicated().sum()

np.int64(0)

In [87]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
cols=['student_id','gender','part_time_job','diet_quality','parental_education_level','extracurricular_participation','internet_quality']
for i in cols:
  df[i]=le.fit_transform(df[i])

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 909 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     909 non-null    int64
 1   age                            909 non-null    int64
 2   gender                         909 non-null    int64
 3   study_hours_per_day            909 non-null    float64
 4   social_media_hours             909 non-null    float64
 5   netflix_hours                  909 non-null    float64
 6   part_time_job                  909 non-null    int64
 7   attendance_percentage          909 non-null    float64
 8   sleep_hours                    909 non-null    float64
 9   diet_quality                   909 non-null    int64
 10  exercise_frequency             909 non-null    int64
 11  parental_education_level       909 non-null    int64
 12  internet_quality               909 non-null    int64
 13  mental_health_rating           909 non-null    int64
 14  extracurricular_participation  909 non-null    int64
 15  exam_score                     909 non-null    float64
dtypes: float64(6), int64(10)
memory usage: 120.7 KB

In [89]:
x=df.drop('exam_score',axis=1)
y=df['exam_score']

In [90]:
from sklearn.model_selection import train_test_split
# train_test_split()
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [91]:
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train_scaled =sc.fit_transform(X_train)
X_test_scaled =sc.transform(X_test)

In [92]:
#from sklearn.metrics import r2_score#,mean_absolute_error,mean_squared_error
# def evaluate(model,X_train, X_test, y_train, y_test):
#     train_pred =model.predict(X_train)
#     test_pred =model.predict(X_test)
#     print(f"Accuracy for your {model} is:")
#     print(f"accuracy_acore for training {model} is {r2_score(y_train,train_pred)}")
#     print(f"r2_score for testing {model} is {r2_score(y_test,test_pred)}")

In [93]:
from sklearn.linear_model import LinearRegression
# le_model = LinearRegression()
# le_model.fit(X_train_scaled,y_train)
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
y_pred_lr

array([ 61.60067266,  51.38753428,  71.14094937,  70.80669008,
        86.98999563,  63.56665949,  78.53037365,  94.40642827,
        66.01821759,  67.55514934,  56.78800322,  76.3742591 ,
        57.67028858,  49.94451447,  77.61487219,  76.45466173,
        49.47759004,  90.09469526,  84.22249391,  65.10592917,
        74.55027281,  98.49714785,  54.70540602,  67.90690049,
        82.22948814,  63.75121456, 104.79890405,  76.72323144,
        60.4635449 , 103.48909927,  60.96058472,  81.59936434,
        54.69715581,  64.2466328 ,  61.79635471,  64.72501281,
        98.08044039,  57.01558553,  60.74997575,  74.17457734,
        60.61876466,  84.32292101,  69.70431927,  70.09797831,
        88.24747451,  72.17390099,  48.5252329 , 100.69692678,
        79.87302285,  79.39172553,  63.5042162 ,  47.22947658,
        65.12822342,  73.38678991,  69.58187915, 103.67116298,
        69.43796062,  59.36361443,  80.56235723,  58.17445551,
        73.75067768,  70.99314941,  50.15644811,  82.86545945,
        65.52763577,  81.39562946,  63.24591209,  64.53415199,
        43.37202797,  70.49660695,  58.95933976,  59.92063137,
        56.02753773,  78.41888282,  68.11589722,  60.25114368,
        59.3184963 , 112.08485993,  26.78265361,  78.15586091,
        84.42287229,  88.34483471,  74.56042586,  68.17595749,
       101.58613088, 102.31591593,  73.46860624,  71.40508286,
        60.73076958,  60.49197044,  96.02377641,  88.0976698 ,
        86.35228154,  49.35279473,  63.42837983,  53.37034146,
        89.19541177,  74.80382008,  94.54893924,  74.11984554,
        43.65523316,  53.04699295,  75.23747135,  60.18154019,
        61.63309172,  69.40689534,  75.35383167,  75.80339438,
        90.03509895,  69.37884423,  94.0344882 ,  64.72199276,
        51.84753615, 105.29825934,  68.88062555,  49.34958815,
        76.01742832,  73.04658281,  84.83867369,  56.31324014,
        73.22979769, 122.66695662,  85.97308723,  63.4298043 ,
        57.54317782,  61.96106565,  52.36904838,  60.49592464,
        70.03530922,  97.23997004,  44.50467401,  70.33817982,
        43.25069491,  78.38391285,  86.95191234,  84.67084096,
        61.2036953 ,  72.98235012,  63.3041581 ,  55.46793385,
        75.6208411 ,  59.98948914,  73.02357243,  49.88596474,
        67.24927537,  64.56918426,  49.08208083,  72.15947781,
        42.81855322,  31.11421776,  83.79924339,  75.20253951,
        52.75637242,  68.88810768,  69.59790067,  45.86576242,
        82.19039212,  86.34521792,  56.93250683,  91.28014897,
        75.11813203,  82.16592269,  77.78452825,  67.76005439,
        87.16935505,  51.81883923,  91.05211459,  63.58930412,
       107.86075063,  77.48809281,  82.01251983,  70.55572015,
        72.93203791,  88.96310288,  78.36119371,  67.44116747,
        57.69183881,  62.85856071,  53.12139955,  84.67549391,
        90.79973898,  60.88910123])

In [94]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
ridge = Ridge()

In [95]:
ridge_param={
    'alpha':[0.1,1,5,10,50,100]
}
rigid_search = GridSearchCV(ridge,ridge_param,cv=5)
rigid_search.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100]})

In [96]:
rigid_search= rigid_search.predict(X_test)
rigid_search

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but Ridge was fitted without feature names
  warnings.warn(

array([ 40.73953222, 164.40970804, 197.03447346, 113.82687203,
       113.10949032,  66.33816197, 186.79718395, 282.46744702,
        47.72948078,  97.41773827, 132.51986105,  79.78637984,
       264.29125794, 216.19332611, 250.81951341, 119.80310109,
       267.49330729, 220.30269319, 153.63279563, 164.75350518,
       209.82415096, 266.49266502, 198.73669396, 187.40954377,
       188.52209647,  90.76937091, 269.30122401, 148.74165207,
       133.25723905, 261.3560176 , 264.31528053, 201.67393265,
       212.74544533, 106.94314961, 199.4812185 , 116.83354046,
       181.30867017, 254.83582465, 200.94918166, 167.04436514,
       234.8180154 , 215.89632644, 264.13997368, 250.34714334,
       139.39546991, 242.15158124, 158.98481538, 329.95888344,
       221.47756693, 220.09970443, 108.29691518,  86.50803308,
       166.45082371, 162.83164596, 215.04713903, 343.04513562,
       270.68076879, 211.74354463, 108.01448623, 111.91317866,
        68.04740786, 301.02961785,  97.76970034, 159.85042221,
       248.31379125, 259.58331907,  73.89443786, 125.31416206,
        24.71454025, 221.87523473, 136.94143401,  36.26111243,
       154.62934878, 126.14157966, 224.12743586, 156.64099212,
        73.05057602, 305.97956821,  18.74021277, 291.80497438,
       226.32560819, 259.86735731, 228.3911878 , 248.09873467,
       310.85484797, 248.48224152, 241.79334467, 175.35932038,
       241.50000733,  92.1688978 , 281.66345279, 150.09588223,
       257.11047423, 199.34804123, 152.0479924 , 118.37799958,
       110.65513152, 263.33716303, 293.15941143, 230.03041237,
       210.63751373, 217.55795109, 198.36191897,  61.83863573,
       196.2482879 , 152.99493759,  97.90993428, 175.01481741,
       125.90082575, 148.04594272, 277.13351764, 213.89463302,
       225.0112889 , 195.09163852, 231.76549468,  53.60625202,
       164.08502313, 190.1503584 ,  84.8533497 , 250.12251788,
        98.43953922, 374.71436532, 239.90228297, 113.72801101,
       125.80943401, 220.1018483 , 188.48199041, 262.9041221 ,
       251.8828929 , 291.81394147, 212.80879492, 200.18968509,
       118.15477639, 189.13846973, 222.40882705, 308.83181747,
       167.87950251, 137.33607293, 112.6541233 , 183.73578548,
       110.57926658, 174.71727306, 194.65444754, 248.94795044,
       109.7107967 , 118.74878449,  52.67156498, 215.12660132,
         9.50906839, 153.42934716, 201.54963163, 282.90734102,
       267.06064378, 109.93109275, 215.43619332, 119.74638159,
       111.56800056, 302.94072032, 273.44175793, 234.22731112,
       269.08417068, 291.6278043 , 241.33070085, 203.36590492,
       242.48294404,  99.15054152, 112.64113224, 153.98622876,
       339.1334055 , 303.02932353, 168.41700959, 162.24959768,
       189.27088544, 119.86309934, 297.21314084,  93.35358999,
        62.61057481, 100.57597869,  51.69392598, 204.87121898,
       139.17212792, 268.76368105])

In [97]:
from sklearn.linear_model import Lasso
model_lasso = Lasso(alpha=0.1)
lasso_param = {
    'alpha':[0,1,2,3,5,10,15,20]
}

In [98]:
lasso_search = GridSearchCV(model_lasso,lasso_param,cv=5)
lasso_search.fit(X_train_scaled,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.925e+03, tolerance: 1.657e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.209e+03, tolerance: 1.608e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.154e+03, tolerance: 1.712e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.414e+03, tolerance: 1.714e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.139e+03, tolerance: 1.722e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.027e+04, tolerance: 2.104e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5, estimator=Lasso(alpha=0.1),
             param_grid={'alpha': [0, 1, 2, 3, 5, 10, 15, 20]})

In [99]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=200)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
y_pred_rf

array([61.583 , 50.492 , 69.247 , 70.056 , 96.1055, 61.618 , 75.031 ,
       90.619 , 71.459 , 68.8415, 58.0375, 76.878 , 54.2155, 50.8135,
       78.03  , 76.1035, 45.2535, 88.334 , 85.262 , 66.2625, 74.8465,
       96.8695, 52.641 , 69.1345, 81.7755, 60.0115, 97.146 , 72.178 ,
       51.335 , 95.6985, 61.4875, 82.705 , 57.0575, 63.748 , 65.799 ,
       70.149 , 95.816 , 55.9575, 65.6985, 73.915 , 58.792 , 83.278 ,
       72.3825, 74.1135, 80.6585, 72.142 , 45.48  , 94.085 , 76.143 ,
       80.2535, 64.319 , 45.5725, 64.6235, 71.774 , 73.1715, 96.669 ,
       72.7695, 62.9315, 80.9095, 57.0125, 78.504 , 71.2425, 57.326 ,
       83.547 , 57.374 , 80.7095, 65.9505, 67.435 , 43.5415, 68.136 ,
       63.9965, 66.337 , 47.9585, 77.0305, 65.646 , 66.013 , 60.4895,
       99.58  , 34.584 , 78.3795, 88.832 , 85.3695, 77.01  , 68.0455,
       96.8385, 97.8605, 71.068 , 68.735 , 63.366 , 62.679 , 92.9065,
       82.876 , 89.2155, 48.475 , 65.536 , 57.551 , 83.2575, 71.926 ,
       91.3715, 75.4215, 41.4695, 48.365 , 70.964 , 58.8275, 62.9755,
       72.986 , 72.901 , 76.652 , 82.291 , 70.3775, 87.814 , 65.2585,
       55.435 , 98.4195, 69.138 , 54.056 , 68.6345, 70.775 , 81.2625,
       55.738 , 73.9   , 97.222 , 87.9925, 65.1665, 55.2795, 66.725 ,
       55.797 , 59.806 , 70.2365, 96.139 , 43.2385, 74.4725, 47.778 ,
       76.8235, 81.546 , 84.623 , 53.0175, 73.766 , 62.028 , 56.731 ,
       69.3445, 61.067 , 70.7915, 55.9185, 70.1285, 64.2845, 53.4285,
       70.558 , 44.521 , 35.869 , 81.0155, 72.019 , 59.677 , 73.1235,
       69.5315, 48.8385, 76.314 , 77.8575, 62.262 , 92.861 , 75.9815,
       76.455 , 77.359 , 66.265 , 91.065 , 54.369 , 92.917 , 65.0265,
       94.9005, 76.4395, 77.73  , 71.78  , 72.3395, 95.388 , 76.082 ,
       66.5905, 56.8095, 68.1925, 57.5685, 89.7875, 82.863 , 58.332 ])

In [100]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor(max_depth=5)
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)
y_pred_dt

array([ 69.65333333,  43.20322581,  69.44565217,  69.65333333,
       100.        ,  58.55744681,  75.36      ,  92.15777778,
        73.89333333,  69.65333333,  58.55744681,  75.36      ,
        46.75333333,  47.4625    ,  71.62380952,  81.4125    ,
        43.20322581,  86.553125  ,  86.553125  ,  69.44565217,
        75.36      ,  96.57142857,  55.88571429,  69.65333333,
        69.44565217,  58.55744681,  99.08888889,  67.88157895,
        53.27058824,  92.15777778,  58.55744681,  86.553125  ,
        67.88157895,  61.02413793,  61.02413793,  73.89333333,
        92.15777778,  58.55744681,  67.88157895,  69.44565217,
        58.55744681,  78.29807692,  71.62380952,  78.29807692,
        69.44565217,  73.89333333,  46.75333333,  99.08888889,
        81.4125    ,  84.05833333,  67.88157895,  53.27058824,
        67.88157895,  81.4125    ,  69.65333333,  99.08888889,
        69.44565217,  69.65333333,  78.29807692,  58.55744681,
        69.44565217,  73.89333333,  67.88157895,  84.05833333,
        38.03333333,  86.553125  ,  61.02413793,  69.65333333,
        43.20322581,  69.65333333,  69.44565217,  61.63243243,
        53.27058824,  86.553125  ,  69.65333333,  69.44565217,
        61.02413793,  99.08888889,  31.48125   ,  86.553125  ,
        80.48      ,  84.05833333,  81.4125    ,  61.63243243,
        99.08888889,  99.08888889,  69.44565217,  69.44565217,
        61.63243243,  69.65333333,  92.15777778,  81.4125    ,
        92.15777778,  53.27058824,  61.63243243,  61.02413793,
        71.62380952,  73.89333333,  86.553125  ,  81.4125    ,
        43.20322581,  38.03333333,  67.88157895,  58.55744681,
        61.02413793,  81.4125    ,  92.15      ,  92.15      ,
        86.553125  ,  67.88157895,  86.553125  ,  67.88157895,
        58.55744681,  99.08888889,  69.65333333,  46.3       ,
        67.88157895,  67.88157895,  75.36      ,  58.55744681,
        69.44565217,  99.08888889,  92.15777778,  67.88157895,
        58.23333333,  69.65333333,  58.55744681,  58.55744681,
        81.4125    ,  99.08888889,  53.27058824,  75.36      ,
        43.20322581,  78.        ,  69.44565217,  92.15777778,
        47.4625    ,  73.89333333,  67.88157895,  58.55744681,
        67.88157895,  58.55744681,  69.44565217,  58.55744681,
        67.88157895,  69.44565217,  61.02413793,  69.44565217,
        43.20322581,  31.48125   ,  75.36      ,  78.29807692,
        61.02413793,  71.62380952,  67.88157895,  43.20322581,
        78.29807692,  69.65333333,  61.63243243,  94.42142857,
        71.62380952,  69.65333333,  71.62380952,  67.88157895,
        94.42142857,  46.75333333,  80.48      ,  61.63243243,
        96.57142857,  69.65333333,  78.29807692,  71.62380952,
        78.29807692, 100.        ,  69.65333333,  61.63243243,
        58.55744681,  61.63243243,  61.63243243,  92.15777778,
        75.36      ,  58.55744681])

In [101]:
from xgboost import XGBRegressor
model = XGBRegressor()
model.fit(X_train, y_train)

y_pred_xgb = model.predict(X_test)
y_pred_xgb

array([ 62.92224 ,  49.557632,  68.4327  ,  68.88956 ,  95.93622 ,
        60.37129 ,  78.91636 ,  87.31607 ,  67.7544  ,  71.080925,
        56.24093 ,  71.34189 ,  51.3237  ,  53.010372,  77.914955,
        80.35398 ,  48.925636,  87.121475,  88.84658 ,  66.09229 ,
        74.907074,  93.46608 ,  60.16489 ,  68.55024 ,  79.75778 ,
        63.371197, 102.423515,  76.18224 ,  54.050335,  98.5837  ,
        63.632362,  80.600006,  56.27476 ,  63.24612 ,  62.410175,
        66.496574,  97.279015,  53.30563 ,  63.766502,  73.839195,
        59.69639 ,  85.95819 ,  73.3544  ,  80.59475 ,  79.99257 ,
        78.16757 ,  43.792957,  94.32256 ,  76.024666,  74.66519 ,
        60.758423,  46.365574,  62.303585,  73.80003 ,  70.03816 ,
       100.14159 ,  68.568375,  56.16389 ,  85.688934,  55.63997 ,
        71.581436,  75.509476,  52.35606 ,  82.70377 ,  58.054058,
        81.83194 ,  67.110245,  66.79981 ,  41.246387,  73.43784 ,
        61.448532,  64.67353 ,  49.194637,  78.30034 ,  68.67351 ,
        66.29146 ,  60.171494, 102.67939 ,  28.295881,  83.289825,
        90.95878 ,  82.394104,  78.13864 ,  69.991646,  90.96859 ,
       101.29607 ,  71.3476  ,  65.264275,  62.035286,  60.842094,
        93.76798 ,  85.499664,  92.25221 ,  46.903324,  62.887657,
        52.712833,  81.31314 ,  71.888695,  97.477936,  75.900215,
        43.4725  ,  50.827034,  75.74667 ,  60.706783,  58.588665,
        71.89673 ,  72.62369 ,  80.42494 ,  87.47822 ,  72.46445 ,
        95.89061 ,  64.710396,  56.050453,  99.73094 ,  69.561386,
        51.587456,  71.493225,  72.0239  ,  81.38032 ,  57.41758 ,
        74.86538 ,  96.369576,  88.29335 ,  65.07646 ,  53.40941 ,
        66.7208  ,  51.838215,  69.92914 ,  69.41525 ,  96.43212 ,
        44.122265,  73.25852 ,  42.45084 ,  75.43612 ,  82.350815,
        86.63658 ,  53.144535,  78.77343 ,  61.131844,  54.78809 ,
        70.44542 ,  56.93794 ,  71.69321 ,  60.97518 ,  69.71249 ,
        62.259617,  46.589664,  71.62181 ,  40.436543,  29.16311 ,
        82.59463 ,  70.23499 ,  53.533707,  67.152115,  69.59609 ,
        41.355366,  81.90981 ,  80.30684 ,  60.098843,  89.69266 ,
        75.478806,  80.6086  ,  76.93828 ,  71.12339 ,  89.20861 ,
        48.605686,  95.20239 ,  65.67644 ,  96.64325 ,  75.186516,
        79.00681 ,  75.533295,  76.41361 ,  81.321266,  75.65039 ,
        66.26751 ,  54.99827 ,  66.400894,  55.720993,  86.03326 ,
        82.86212 ,  61.19898 ], dtype=float32)

In [103]:
models = {
    "Linear": LinearRegression(),
    "Ridge": Ridge(),
    "lasso": Lasso(),
    "RandomForest": RandomForestRegressor(),
    "DecisionTree": DecisionTreeRegressor(),
    "XGBoost": XGBRegressor()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(name, r2_score(y_test, pred))

Linear 0.8881336475406082
Ridge 0.8881531272563801
lasso 0.8793905482140518
RandomForest 0.8784924255823309
DecisionTree 0.6536395102839923
XGBoost 0.8779347727681361

In [106]:
import pickle

pickle.dump(rf, open("model.pkl", "wb"))
pickle.dump(sc, open("scaler.pkl", "wb"))